name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application Windows
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.10'
        spec: './vss-live-plot.spec'
        requirements: './requirements.txt'
        upload_exe_with_name: 'vss-live-plot.exe'
        options: --onefile --hidden-import=matplotlib --hidden-import=numpy
        
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application Linux
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.10'
        spec: './vss-live-plot.spec'
        requirements: './requirements.txt'
        upload_exe_with_name: 'vss-live-plot'
        options: --onefile --hidden-import=matplotlib --hidden-import=numpy
