name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: vss-live-plot
        path: ./dist/windows
        if-no-files-found: error
        
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: vss-live-plot
        path: ./dist/linux
        if-no-files-found: error
